src/task_tracker/src/dashboard/urls.py
from dashboard import views as dashboard_views
from django.urls import path


app_name = "dashboard"
urlpatterns = [
    path("task/create/", dashboard_views.TaskCreateView.as_view(), name="task_create"),
    path("task/complete/<int:pk>/", dashboard_views.TaskCompleteView.as_view(), name="task_complete"),
    path("task/delete/<int:pk>/", dashboard_views.TaskDeleteView.as_view(), name="task_delete"),
    path("task/update/<int:pk>/", dashboard_views.TaskUpdateView.as_view(), name="task_update"),
    path("tasks/", dashboard_views.TaskListView.as_view(), name="task_list"),
]

src/task_tracker/src/task_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from dashboard import views as dashboard_views
from task_tracker import views as tt_views


urlpatterns = [
    path("dashboard/", include("dashboard.urls", namespace="dashboard")),
    path("accounts/login/", tt_views.TTLoginView.as_view(), name="login"),
    path("admin/", admin.site.urls),
    path("", dashboard_views.TaskListView.as_view()),
    path("", include("social_django.urls", namespace="social")),
]

src/task_tracker/src/dashboard/models.py
from django.conf import settings
from django.db import models

# Create your models here.


class Task(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="authored_tasks",
    )
    assignee = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        related_name="assigned_tasks",
        null=True,
        blank=True,
    )
    title = models.TextField()
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)

src/task_tracker/src/dashboard/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["title", "description", "is_completed", "assignee"]
        widgets = {
            "assignee": forms.Select(attrs={"placeholder": "Choose assignee"}),
            "is_completed": forms.CheckboxInput(),
            "title": forms.TextInput(
                attrs={"placeholder": "Title", "size": "40", "maxlength": "100"}
            ),
        }

    def __init__(self, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)
        self.fields["assignee"].queryset = User.objects.filter(is_active=True)
        self.fields["assignee"].label_from_instance = lambda obj: obj.email

src/task_tracker/src/dashboard/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views.generic import View
from django.urls import reverse_lazy
from django.views.generic.edit import UpdateView, DeleteView
from django.db.models.functions import Now

from dashboard import forms as dashboard_forms
from dashboard import models as dashboard_models


# Create your views here.
class TaskListView(LoginRequiredMixin, View):
    def get(self, request):
        authored_tasks = dashboard_models.Task.objects.filter(author_id=request.user)
        assigned_tasks = dashboard_models.Task.objects.filter(assignee_id=request.user)
        return render(
            request,
            "task_list.html",
            {"authored_tasks": authored_tasks, "assigned_tasks": assigned_tasks},
        )


class TaskCreateView(LoginRequiredMixin, View):
    def get(self, request):
        form = dashboard_forms.TaskForm()
        return render(request, "task_create.html", {'form': form})

    def post(self, request):
        form = dashboard_forms.TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.author = request.user
            task.save()
            return redirect("dashboard:task_list")
        else:
            form = dashboard_forms.TaskForm(request.POST)
            return render(request, "task_create.html", {'form': form})


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = dashboard_models.Task
    success_url = reverse_lazy("dashboard:task_list")
    template_name = "task_list.html"
    context_object_name = "task"
    # def get(self, request, task_id):
    #     task = dashboard_models.Task.objects.get(id=task_id)
    #     task.delete()
    #     return redirect("dashboard:task_list")


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = dashboard_models.Task
    form_class = dashboard_forms.TaskForm
    template_name = "task_update.html"
    context_object_name = "task"
    success_url = reverse_lazy("dashboard:task_list")

    # def get(self, request, task_id):
    #     task = dashboard_models.Task.objects.get(id=task_id)
    #     form = dashboard_forms.TaskForm(instance=task)
    #     return render(request, "task_update.html", {'form': form})

    # def post(self, request, task_id):
    #     task = dashboard_models.Task.objects.get(id=task_id)
    #     form = dashboard_forms.TaskForm(request.POST, instance=task)
    #     if form.is_valid():
    #         form.save()
    #         return redirect("dashboard:task_list")
    #     else:
    #         form = dashboard_forms.TaskForm(request.POST, instance=task)
    #     return render(request, "task_update.html", {'form': form})


class TaskCompleteView(LoginRequiredMixin, View):
    # model = dashboard_models.Task
    # fields = ["is_completed"]
    # template_name = "task_list.html"
    # success_url = reverse_lazy("dashboard:task_list")
    def post(self, *args, **kwargs):
        task_id = kwargs.get("pk")
        task = dashboard_models.Task.objects.get(id=task_id)

        task.is_completed = True
        task.completed_at = Now()
        task.save()

        return redirect("dashboard:task_list")

src/task_tracker/src/task_tracker/views.py
from django.contrib.auth.views import LoginView


# Create your views here.
class TTLoginView(LoginView):
    template_name = 'users/login.html'
    success_url = '/'

src/task_tracker/src/dashboard/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Мой сайт{% endblock %}</title>
    {% block extra_head %}{% endblock %}
  </head>
  <body>
    <header>
      Email: {{ request.user.email }}
      <nav>
        <ul>
          <li><a href="">Assigned to me</a></li>
          <li><a href="">Created by me</a></li>
        </ul>
      </nav>
    </header>

    <main>
      {% block content %}{% endblock content %}
    </main>

    <footer>
      {% block footer %}
      &copy; Popug Task Tracker
      {% endblock footer %}
    </footer>

    {% block extra_scripts %}{% endblock %}
  </body>
</html>

src/task_tracker/src/dashboard/templates/create_task.html
{% extends 'base.html' %}

{% block content %}
<div>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Добавить задачу">
  </form>
</div>
{% endblock %}

src/task_tracker/src/dashboard/templates/task_create.html
{% extends 'base.html' %}

{% block content %}
<div>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Добавить задачу">
  </form>
</div>
{% endblock %}

src/task_tracker/src/dashboard/templates/task_list.html
{% extends "base.html" %}

{% block content %}
<a href="{% url 'dashboard:task_create' %}">Create Task</a>
<!-- dashboard.html -->
<h2>Created Tasks</h2>
<ul>
{% for task in authored_tasks %}
    <li>{{ task }}</li>
{% empty %}
    <li>No tasks created.</li>
{% endfor %}
</ul>

<!-- tasks_list.html -->
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Created At</th>
            <th>Completed At</th>
            <th>Is Completed</th>
            <th>Edit</th>
            <th>Delete</th>
            <th>Mark Completed</th>
        </tr>
    </thead>
    <tbody>
    {% for task in assigned_tasks %}
        <tr>
            <td>{{ task.id }}</td>
            <td>{{ task.title }}</td>
            <td>{{ task.created_at }}</td>
            {% if task.is_completed %}
            <td>{{ task.completed_at }}</td>
            {% endif %}
            <td>{{ task.is_completed|yesno:"Yes,No" }}</td>
            <td>
                <a href="{% url 'dashboard:task_update' task.id %}">Edit</a>
            </td>
            <td>
                <form method="post" action="{% url 'dashboard:task_delete' task.id %}">
                    {% csrf_token %}
                    <button type="submit">Delete</button>
                </form>
            </td>
            <td>
                {% if not task.is_completed %}
                    <form method="post" action="{% url 'dashboard:task_complete' task.id %}">
                        {% csrf_token %}
                        <button type="submit">Mark Completed</button>
                    </form>
                {% endif %}
            </td>
        </tr>
    {% empty %}
        <tr>
            <td colspan="8">No tasks available</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

src/task_tracker/src/dashboard/templates/task_update.html
{% extends 'base.html' %}

{% block content %}
<div>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Сохранить">
  </form>
</div>
{% endblock %}

src/task_tracker/src/task_tracker/templates/users/login.html
{% extends "base.html" %}

{% block content %}
<form method="post" action="{% url 'login' %}">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Login" />
</form>

<div>
    <p>Войти с помощью социальной сети:</p>
    <a href="{% url 'social:begin' 'popug_oauth2' %}">Popug Oauth2</a>
</div>
{% endblock %}